common:
  # yv-development-cb (works for youversion-web.dev)
  # facebook_app_id: 306713076033387
  # facebook_secret: 1a8bf87913629f4162b6c91e5fe943a2
  # Bible Test App (bible.dev)
  facebook_app_id: 818055158234752
  facebook_secret: 05d219f1c41d63f8ef34dd404cccb64d
  twitter_key: KobF6Lt0zWDFBDxZgZyg
  twitter_secret: GVXSAfboriqOLFDl6Ux1h9pJpDflkRKTzhap6pUOIOs
  avatar_path: https://d5xlnxqvcdji7.cloudfront.net/users/images/
  #note: this direct path will not work for users without avatars (404's)
  #workaround should be coming by EOY 2012
  avatar_path_direct: https://static-youversionapi-com.s3.amazonaws.com/users/images/
  api_root: youversionapi.com
  api_referer: web-dev.youversionapi.com
  api_version: "3.1"
  memcache_server: localhost
  # Prod
  smartling_api_key: 'df76c884-977f-4262-8650-423119eedaba'
  smartling_project_id: 'b13fafcf3'
  # Sandbox
  # smartling_api_key: 'b3f15261-40d8-4ed3-9a6b-07c5b1ba476a'
  # smartling_project_id: 'a46acf1f4'
  # 
  # Timeouts: all times are in seconds
  api_default_timeout: 10
  rack_execution_timeout: 1000
  #
  # Caching: all times are in minutes
  memoization_cache_expiration: 720
  very_short_cache_expiration: 2
  short_cache_expiration: 10
  long_cache_expiration: 45
  very_long_cache_expiration: 720
  rate_limit: 120

development:
  api_root: youversionapistaging.com
  api_referer: web-dev-local.youversionapistaging.com
  api_version: "3.1"
  api_default_timeout: 15000
  rack_execution_timeout: 15000
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"

staging:
  #api_root: youversionapi.com
  #api_referer: web-dev-staging.youversionapistaging.com
  #api_version: "3.1"
  api_root: youversionapistaging.com
  api_referer: web-dev-local.youversionapistaging.com
  api_version: "3.1"
  api_default_timeout: 15
  rack_execution_timeout: 15
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2

test:
  api_root: youversionapistaging.com
  api_referer: web-dev-tests.youversionapistaging.com
  api_version: "3.1"
  api_default_timeout: 15
  rack_execution_timeout: 15

production:
  api_root: youversionapi.com
  api_referer: web.youversionapi.com
  api_version: "3.1"
  api_default_timeout: 5
  rack_execution_timeout: 22
  memcache_server: memcache.youversion.com
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
