af: 'af-ZA'
ar:  'ar'
bg: 'bg-BG'
ca: 'ca-ES'
cs: 'cs-CZ'
cy: 'cy-GB'
da:  'da-DK'
de:  'de-DE'
en-GB:  'en-GB'
es-ES: 'es-ES'
es: 'es-LA'
fa: 'fa-IR'
fi: 'fi-FI'
fr: 'fr-FR'
hi: 'hi-IN'
hr:  'hr-HR'
hu: 'hu-HU'
id:     'id-ID'
it:    'it-IT'
ja:     'ja-JP'
km:     'km-KH'
ko:     'ko-KR'
lt:     'lt-LT'
lv:    'lv-LV'
mk:     'mk-MK'
ms:     'ms-MY'
my:    'my'
nl:    'nl-NL'
'no':    'no-NO'
pl:    'pl-PL'
pt:    'pt-BR'
pt-PT: 'pt-PT'
ro:     'ro-RO'
ru:    'ru-RU'
sk:     'sk-SK'
sn:    'sn'
sq:     'sq-AL'
sv:    'sv-SE'
sw:    'sw'
ta:    'ta-IN'
th:    'th-TH'
tl:    'tl-PH'
tr:     'tr-TR'
uk:    'uk-UA'
vi:     'vi-VN'
mn:    'xc-MN'
zh-CN:  'zh-CN'
zh-TW: 'zh-TW'