---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: bible
  name: bible
  namespace: bible
spec:
  maxReplicas: 30
  minReplicas: 8
  scaleTargetRef:
    kind: Deployment
    name: production
  targetCPUUtilizationPercentage: 60
