common:
  # yv-development-cb (works for youversion-web.dev)
  # facebook_app_id: 306713076033387
  # facebook_secret: 1a8bf87913629f4162b6c91e5fe943a2
  # Bible Test App (bible.dev)
  facebook_app_id: 818055158234752
  facebook_secret: 05d219f1c41d63f8ef34dd404cccb64d
  twitter_key: KobF6Lt0zWDFBDxZgZyg
  twitter_secret: GVXSAfboriqOLFDl6Ux1h9pJpDflkRKTzhap6pUOIOs
  google_tag_container: GTM-52JZ7N
  avatar_path: https://d5xlnxqvcdji7.cloudfront.net/users/images/
  #note: this direct path will not work for users without avatars (404's)
  #workaround should be coming by EOY 2012
  avatar_path_direct: https://static-youversionapi-com.s3.amazonaws.com/users/images/
  api_root: youversionapi.com
  api_referer: web-dev.youversionapi.com
  api_version: "3.1"
  memcache_server: localhost
  # Prod
  smartling_api_key: 'df76c884-977f-4262-8650-423119eedaba'
  smartling_project_id: 'b13fafcf3'
  # Sandbox
  # smartling_api_key: 'b3f15261-40d8-4ed3-9a6b-07c5b1ba476a'
  # smartling_project_id: 'a46acf1f4'
  #
  # Timeouts: all times are in seconds
  api_default_timeout: 10
  rack_execution_timeout: 1000
  #
  # Caching: all times are in minutes
  memoization_cache_expiration: 5
  very_short_cache_expiration: 2
  short_cache_expiration: 10
  long_cache_expiration: 45
  longer_cache_expiration: 240
  very_long_cache_expiration: 720
  rate_limit: 120
  treadstone_base_url: 'https://yv-giving-staging.life.church/'
  vod_image_api_url: 'https://s3.amazonaws.com/votd-images-youversionapi-com/items.json'
  branch_key: "key_test_kfexIKCVofZXO9YVmsronefnABfGz4ta"
  nodejs_import_url: "http://localhost:3000/featureImport"
  nodejs_api_host: "nodejs-staging.bible.com"
  nodejs_ping_host: "localhost"
  nodejs_ping_port: "3000"
  google_signin_client_id: "201895780642-ln00r1cev5fp6u3eqpq07olmi2dabmkl.apps.googleusercontent.com"
  google_signin_scope: "profile email"
  facebook_signin_scope: "public_profile,email"
  facebook_signin_app_id: "117344358296665"
  facebook_signin_app_secret: "8cc85686e4ff71fe0ee8de801dd5d7f3"
  # Sentry/Raven DSN defaults to "YouVersion Web / Production" (historically):
  sentry_dsn: "https://eddeeff44cf84a31b214e9530c200f5a:fec04d30688c4d79b7e1a5be0cd4df18@app.getsentry.com/6470"

development:
#  api_root: youversionapi.com
#  api_referer: web.youversionapi.com
#  api_version: "3.1"
  api_root: youversionapistaging.com
  api_referer: web-dev-local.youversionapistaging.com
  api_version: "3.1"
  api_default_timeout: 15000
  rack_execution_timeout: 15000
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  branch_key: "key_test_kfexIKCVofZXO9YVmsronefnABfGz4ta"
  nodejs_import_url: "http://localhost:3000/featureImport"
  nodejs_api_host: "localhost"
  nodejs_api_port: "3000"
  # Use alternate Sentry DSN ("YouVersion Web / Dev") in development environments:
  sentry_dsn: "https://fd471bea250d42a6981047c9656bf735:a3292ab70935413c9e8b386d84b19f39@sentry.io/305258"


staging:
  api_root: youversionapistaging.com
  api_referer: web-dev-staging.youversionapistaging.com
  api_version: "3.1"
  api_default_timeout: 15
  rack_execution_timeout: 15
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
  branch_key: "key_test_kfexIKCVofZXO9YVmsronefnABfGz4ta"
  nodejs_api_host: "nodejs-staging.bible.com"

review:
  api_root: youversionapistaging.com
  api_referer: web-dev-review.youversionapistaging.com
  api_version: "3.1"
  api_default_timeout: 15
  rack_execution_timeout: 15
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
  branch_key: "key_test_kfexIKCVofZXO9YVmsronefnABfGz4ta"
  nodejs_api_host: "nodejs-review.bible.com"

test:
  api_root: youversionapistaging.com
  api_referer: web-dev-tests.youversionapistaging.com
  api_version: "3.1"
  api_default_timeout: 15
  rack_execution_timeout: 15

production:
  api_root: youversionapi.com
  api_referer: web.youversionapi.com
  api_version: "3.1"
  api_default_timeout: 10
  google_tag_container: GTM-NPBBBK
  rack_execution_timeout: 22
  twitter_key: "HhYNsW1KCxFH5WeCQ3nRXQ"
  twitter_secret: "LppBTdEyoJ3ASfPqxHz97IDW5UxpXVim2DbrqdJSrTI"
  facebook_app_id: 105030176203924
  facebook_secret: 9d03678ddd8b5588c4e6c91bd996cce2
  treadstone_base_url: 'https://donate.bible.com/'
  branch_key: "key_live_jpmoQCKshT4dmEI1OZyuGmlmjffQNTlA"
  nodejs_api_host: "nodejs.bible.com"
  google_signin_client_id: "201895780642-g4oj7hm4p3h81eg7b1di2l2l93k5gcm3.apps.googleusercontent.com"
